### ISSUE TITLE
Innoextract missing?

### ISSUE THREAD

**Issue by lunaryorn** [flathub/io.github.sharkwouter.Minigalaxy#29]
It looks as if minigalaxy uses innoextract for some Windows games (see https://github.com/sharkwouter/minigalaxy/issues/435 and https://github.com/sharkwouter/minigalaxy/blob/f86daf86ebf99862f08f7186bf2ea893a9b5e7ac/minigalaxy/installer.py#L150), but innoextract seems to be missing in this package 🤔 

Could it be added?

**Comment by tim77** [comment]
Thanks for reporting! Please try [test build](https://github.com/flathub/io.github.sharkwouter.Minigalaxy/pull/30).

**Comment by lunaryorn** [comment]
It didn't fix [my issue](https://github.com/sharkwouter/minigalaxy/issues/547), but I see a running innoextract process while installing the game, so I guess innoextract itself works 👍🏿 🙏🏿

**Comment by lunaryorn** [comment]
So I guess this is fixed now?

**Comment by tim77** [comment]
> So I guess this is fixed now?

Need confirmation from you. Look like problem is still exist for you and not solved for 100%. I only did quick test and would be nice of other people helps with testing.

**Comment by lunaryorn** [comment]
`innoextract` is present; my issue is unrelated, I believe.  I for my part consider this solved 🙂

**Comment by tim77** [comment]
Great! Please reopen if something still must be done on build side.
